import Head from 'next/head'
import Link from 'next/link';
import { getAllPublished } from './notion';
import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  // console.log(posts)
  if (posts.length === 0) return <>
    <main>
      <h1 className='text-center my-3'>Blogs</h1>
      <section className='p-3 my-4 shadow-sm p-3 mb-5 bg-body-tertiaryborder rounded'>
        <p className='text-center my-3'>No posts</p>
      </section>

    </main>
  </>

  return (
    <div className={styles.container}>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className='text-center'>Blogs</h1>
        <div className="container">
          {posts.map((post, index) => (
            <section key={index} className='p-3 my-4 shadow-sm p-3 mb-5 bg-body-tertiaryborder rounded'>
              <div>
                <h2>
                  <Link href={post.slug} className='text-reset'>
                    {post.title}
                  </Link>
                </h2>
              </div>
              <div>{post.date}</div>
              <p>{post.description.substr(0, 100) + " . . ."}</p>
            </section>
          ))}

        </div>
      </main >
    </div >
  )
}

export const getStaticProps = async () => {
  const data = await getAllPublished()

  return {
    props: {
      posts: data,
    },
    revalidate: 60
  };
};
